export const phases = [
  {
    id: "foundation",
    order: 1,
    days: "Day 1–30",
    eyebrow: "はじまりの平原",
    title: "LLM基礎とRAG",
    icon: "✦",
    color: "#70d6a2",
    summary: "LLMの言葉を理解し、検索して答える最初の仕組みを組み立てる。",
    skills: ["Token / Embedding", "Structured Output", "RAG", "Tool Calling"],
    quests: [
      {
        id: "first-call",
        title: "最初の召喚",
        type: "基礎",
        duration: 45,
        xp: 120,
        description: "API、環境変数、構造化出力を理解し、安定したJSONを返す。",
        objectives: ["APIキーを安全に環境変数へ置く", "Pydanticで出力形式を定義する", "失敗時の挙動を説明する"],
        source: "README: APIと構造化出力",
      },
      {
        id: "rag-seed",
        title: "知識の種を探せ",
        type: "実装",
        duration: 60,
        xp: 160,
        description: "キーワード検索からEmbedding、ChromaDBまで最小RAGを育てる。",
        objectives: ["検索と生成の責務を分ける", "コサイン類似度を説明する", "根拠文書を回答へ渡す"],
        source: "README: RAGとEmbedding",
      },
      {
        id: "tool-scout",
        title: "道具使いの試練",
        type: "実装",
        duration: 60,
        xp: 180,
        description: "Tool CallingとReActで、考える・動く・観察するループを作る。",
        objectives: ["Toolの引数を構造化する", "実行結果をLLMへ返す", "最大ループ回数を設ける"],
        source: "README: Tool Callingとエージェント",
      },
    ],
  },
  {
    id: "retrieval",
    order: 2,
    days: "Day 31–47",
    eyebrow: "検索者の峡谷",
    title: "検索・評価・内部理解",
    icon: "⌕",
    color: "#73a9ff",
    summary: "勘ではなく指標で検索を比べ、LLMの内部と失敗箇所を説明する。",
    skills: ["BM25 / RRF", "Reranker", "Hit@k / MRR", "Citation評価"],
    quests: [
      {
        id: "hybrid-forge",
        title: "ふたつの検索を鍛えよ",
        type: "比較",
        duration: 60,
        xp: 190,
        description: "BM25とベクトル検索をRRFで統合し、得意分野の違いを測る。",
        objectives: ["BM25の式を説明する", "RRFで順位を統合する", "Hybridの改善を評価する"],
        source: "Curriculum Day 32–37",
      },
      {
        id: "metric-compass",
        title: "評価の羅針盤",
        type: "評価",
        duration: 60,
        xp: 220,
        description: "Hit@k、MRR、Recallで検索失敗と生成失敗を切り分ける。",
        objectives: ["固定評価ケースを用意する", "検索指標を計算する", "失敗カテゴリを記録する"],
        source: "Curriculum Day 38–46",
      },
      {
        id: "citation-oath",
        title: "引用の誓約",
        type: "評価",
        duration: 60,
        xp: 240,
        description: "正解らしさだけでなく、回答が根拠に支えられているかを測る。",
        objectives: ["Groundednessを評価する", "Citation Precisionを計算する", "Citation Recallを計算する"],
        source: "Curriculum Day 40 / 47",
      },
    ],
  },
  {
    id: "production-rag",
    order: 3,
    days: "Day 48–58",
    eyebrow: "知識工房",
    title: "Production RAG",
    icon: "◆",
    color: "#f7c86a",
    summary: "更新でき、引用でき、情報不足なら止まれるRAGを一本につなぐ。",
    skills: ["Metadata Ingest", "Query Rewrite", "Context Builder", "安全な未回答"],
    quests: [
      {
        id: "ingest-craft",
        title: "壊れない知識庫",
        type: "実装",
        duration: 60,
        xp: 260,
        description: "意味境界を守り、metadataとhashを持つ再投入可能なIngestを作る。",
        objectives: ["意味単位でChunkingする", "source・sectionを保持する", "重複と削除を扱う"],
        source: "Curriculum Day 48–51",
      },
      {
        id: "context-alchemy",
        title: "文脈錬成術",
        type: "改善",
        duration: 60,
        xp: 280,
        description: "Query Rewrite、Multi-query、Rerankerで必要な文脈だけを集める。",
        objectives: ["失敗Queryを書き換える", "複数検索結果を統合する", "Token上限内に整える"],
        source: "Curriculum Day 52–55",
      },
      {
        id: "rag-boss",
        title: "ボス：根拠なき回答",
        type: "ボス",
        duration: 90,
        xp: 360,
        description: "引用・未回答・評価を統合し、Production RAG v1を完成させる。",
        objectives: ["source付きで回答する", "根拠なしなら拒否する", "品質・費用・latencyを比較する"],
        source: "Curriculum Day 56–58",
      },
    ],
  },
  {
    id: "safe-agent",
    order: 4,
    days: "Day 59–70",
    eyebrow: "自律機械の遺跡",
    title: "安全なAgent・MCP",
    icon: "⬡",
    color: "#d49cff",
    summary: "動くだけのAgentを、止まり、再開し、承認を待てる仕組みにする。",
    skills: ["Tool Registry", "停止条件", "Checkpoint", "Human-in-the-Loop"],
    quests: [
      {
        id: "tool-guard",
        title: "道具庫の番人",
        type: "安全性",
        duration: 60,
        xp: 280,
        description: "型検証、Allowlist、timeoutで不正なTool実行を防ぐ。",
        objectives: ["Pydanticで引数検証する", "未知Toolを拒否する", "例外を構造化して返す"],
        source: "Curriculum Day 59–63",
      },
      {
        id: "state-maze",
        title: "状態迷宮からの帰還",
        type: "設計",
        duration: 60,
        xp: 310,
        description: "状態機械とCheckpointで、必ず止まり途中から再開できるAgentを作る。",
        objectives: ["node・edge・stateを分ける", "予算で停止する", "SQLiteから再開する"],
        source: "Curriculum Day 64–66",
      },
      {
        id: "approval-gate",
        title: "承認の門",
        type: "ボス",
        duration: 90,
        xp: 380,
        description: "副作用のあるToolを人の承認で制御し、RAGをMCPとして公開する。",
        objectives: ["approve・edit・rejectを実装する", "監査ログを残す", "MCP Toolを公開する"],
        source: "Curriculum Day 67–70",
      },
    ],
  },
  {
    id: "api",
    order: 5,
    days: "Day 71–80",
    eyebrow: "接続都市 API",
    title: "API・データ設計",
    icon: "⇄",
    color: "#ff9f7a",
    summary: "CLIの知能を、認証された他アプリが安全に使えるサービスへ変える。",
    skills: ["FastAPI", "Streaming", "DB / Migration", "認証・ACL"],
    quests: [
      {
        id: "api-gateway",
        title: "外界への門を開く",
        type: "実装",
        duration: 60,
        xp: 300,
        description: "型付きのQuery・Ingest APIとhealth checkを公開する。",
        objectives: ["OpenAPIを確認する", "入力エラーを統一する", "asyncで外部I/Oを扱う"],
        source: "Curriculum Day 71–73",
      },
      {
        id: "stream-vault",
        title: "流れる応答、残る記録",
        type: "設計",
        duration: 60,
        xp: 330,
        description: "SSE、DB、Background Jobで長い処理を扱う。",
        objectives: ["進捗Eventを配信する", "Migrationを作る", "job状態を永続化する"],
        source: "Curriculum Day 74–76",
      },
      {
        id: "acl-boss",
        title: "ボス：権限越境",
        type: "ボス",
        duration: 90,
        xp: 400,
        description: "認証・ACL・耐障害性を結合テストで保証する。",
        objectives: ["他ユーザー文書を遮断する", "timeout・retryを制御する", "主要経路を結合テストする"],
        source: "Curriculum Day 77–80",
      },
    ],
  },
  {
    id: "operations",
    order: 6,
    days: "Day 81–90",
    eyebrow: "観測者の塔",
    title: "Security・運用・Delivery",
    icon: "◉",
    color: "#63d7dc",
    summary: "安全性、品質、速度、費用を見える化し、再現可能に届ける。",
    skills: ["Threat Model", "Trace / Metrics", "SLO", "Docker / CI"],
    quests: [
      {
        id: "threat-map",
        title: "脅威の地図",
        type: "安全性",
        duration: 60,
        xp: 320,
        description: "Trust Boundaryを描き、Injectionと秘密漏洩を固定テストにする。",
        objectives: ["資産と攻撃経路を列挙する", "direct/indirect攻撃を試す", "多層Guardrailを設計する"],
        source: "Curriculum Day 81–83",
      },
      {
        id: "observatory",
        title: "品質観測所",
        type: "運用",
        duration: 60,
        xp: 350,
        description: "Log、Trace、Metricsで1リクエストの品質と費用を追う。",
        objectives: ["秘密なしの構造化Logを出す", "spanで失敗箇所を追う", "SLOを定義する"],
        source: "Curriculum Day 84–88",
      },
      {
        id: "delivery-line",
        title: "再現可能性の砦",
        type: "ボス",
        duration: 90,
        xp: 420,
        description: "DockerとCI/CDで、誰でも同じ品質のアプリを動かせるようにする。",
        objectives: ["1コマンドで起動する", "lint・型・test・evalを通す", "image buildを自動化する"],
        source: "Curriculum Day 89–90",
      },
    ],
  },
  {
    id: "graduation",
    order: 7,
    days: "Day 91–100",
    eyebrow: "最終到達地",
    title: "卒業制作・採用準備",
    icon: "♜",
    color: "#ff7d99",
    summary: "すべての設計判断を一つの完成品に統合し、説明できる証拠を残す。",
    skills: ["Architecture", "統合テスト", "Deployment", "Portfolio"],
    quests: [
      {
        id: "blueprint",
        title: "卒業制作の設計図",
        type: "設計",
        duration: 90,
        xp: 380,
        description: "要件、品質目標、Architecture、脅威モデルを言語化する。",
        objectives: ["user storyと対象外を決める", "責務と依存方向を描く", "設計の代替案を残す"],
        source: "Curriculum Day 91–93",
      },
      {
        id: "integration",
        title: "七つの力を統合せよ",
        type: "実装",
        duration: 120,
        xp: 480,
        description: "RAG、Agent、API、DB、認証、監視を一つのアプリに統合する。",
        objectives: ["Core RAGを統合する", "承認付きAgentを統合する", "品質・攻撃・負荷をテストする"],
        source: "Curriculum Day 94–97",
      },
      {
        id: "final-demo",
        title: "最終クエスト：15分の証明",
        type: "最終ボス",
        duration: 120,
        xp: 600,
        description: "第三者が再現できる形で配布し、設計判断を面接形式で語る。",
        objectives: ["READMEだけでDemoを再現する", "評価結果と制約を示す", "なぜこの設計かを説明する"],
        source: "Curriculum Day 98–100",
      },
    ],
  },
];

export const allQuests = phases.flatMap((phase) =>
  phase.quests.map((quest) => ({ ...quest, phaseId: phase.id, phaseOrder: phase.order })),
);
